### PR TITLE
Remove strict R requirement

### PR DESCRIPTION
**Pull request by dinakar29**
Remove the R >= 4.1 dependency.

### CODE REVIEW

**Review by danielinteractive — APPROVED** [review]
Thanks but maybe still good to require at least 4.0

**Comment by kpagacz** [comment]
I am pretty sure this requirement was in place because hermes required a bioconductor version available from R>=4.1

**Comment by kpagacz** [comment]
Might want to consider reverting this because hermes does not work older versions anyway (at least some of its parts)

**Comment by danielinteractive** [comment]
@kpagacz no, technically I think we only need 4.0 but due to bioccheck we needed to increase and merged this back to main at that time.

**Comment by kpagacz** [comment]
I vaguely remember a bug in S4Vectors v 0.30.1 (bioc 3.13) affecting some functions from hermes. The patched version of S4Vectors comes from bioc 3.14 which is available only for r >= 4.1

Happy to remember wrong.

**Comment by danielinteractive** [comment]
@kpagacz hm when do we find this out? do we have integration tests already running on 4.0?

**Comment by kpagacz** [comment]
I think we do. I suspect the passed tests indicate my memory was playing tricks on me.

**Comment by dinakar29** [comment]
Confirming we have integration tests for R 4.0.3 on BEE here: https://code.roche.com/nest/automation/integration-tests/-/blob/main/.gitlab-ci.yml#L61-68

**Comment by dinakar29** [comment]
Confirming we have integration tests internally for R 4.0.3.

**Pull request merged**
