### PR TITLE
Relevant updates from BioConductor master branch.

### PR DESCRIPTION
**Pull request by danielinteractive**

### CODE REVIEW

**Comment by danielinteractive** [comment]
@dinakar29 small question on customizing linter behavior: I have in this repo a  `md` file that is generated from `Rmd` file (the README). Somehow it introduces additional spaces after list dashes. So I get in the linter the error:
`/github/workspace/README.md:16:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]`
etc.
Is there a way I could add on top of the inherited github workflow linter rules an exception - e.g. either not lint this specific file, or allow for spaces after list markers?
thx for your help :-)

**Comment by dinakar29** [comment]
> @dinakar29 small question on customizing linter behavior: I have in this repo a `md` file that is generated from `Rmd` file (the README). Somehow it introduces additional spaces after list dashes. So I get in the linter the error: `/github/workspace/README.md:16:1 MD030/list-marker-space Spaces after list markers [Expected: 1; Actual: 3]` etc. Is there a way I could add on top of the inherited github workflow linter rules an exception - e.g. either not lint this specific file, or allow for spaces after list markers? thx for your help :-)

This is definitely possible. We can update the default rule on the [`.lintr` configuration](https://github.com/insightsengineering/hermes/blob/main/.lintr) file like so:

```
linters: with_defaults(line_length_linter = line_length_linter(120), object_usage_linter = NULL, cyclocomp_linter = cyclocomp_linter(complexity_limit = 25L), infix_spaces_linter = NULL, spaces_inside_linter = NULL, spaces_left_parentheses_linter = NULL, trailing_whitespace_linter = NULL)
```

**Comment by danielinteractive** [comment]
@dinakar29 thx - however my question was whether we can inherit general linter rules and then customize specifics in this repo? also similar question is then if we can exclude custom repo-specific files from linting?

**Comment by dinakar29** [comment]
> @dinakar29 thx - however my question was whether we can inherit general linter rules and then customize specifics in this repo? also similar question is then if we can exclude custom repo-specific files from linting?

That should be definitely possible. Let me push the corresponding commits on this branch to correct the checks.

**Comment by dinakar29** [comment]
Okay, so there were multiple ways that could have been achieved - I just went with the least intrusive method of simply disabling `markdownlint` for the `README.[R]md` by adding a header to the file to skip linting altogether.

Other ways would have been:

- To include a [`.markdownignore`](https://github.com/igorshubovych/markdownlint-cli#ignoring-files) file for additional file exclusions
- [Ignoring files via headers/markers](https://github.com/igorshubovych/markdownlint-cli#ignoring-files)

What I mentioned in https://github.com/insightsengineering/hermes/pull/157#issuecomment-979934201 was incorrect - that would have worked for R-based linting using `.lintr`, not for markdown.

**Review by BFalquet — APPROVED** [review]
Thank you for the work.

**Pull request merged**
