### PR TITLE
Fix `h_get_size_biomart()` test inconsistencies.

### LINKED ISSUE #163: `h_get_size_biomart` test error on R 4.1.2
**Summary**

The following was encountered while running `R CMD check` for hermes v0.99.2.9006, for R 4.1.2 (rocker)

```r
══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test-connections.R:41:3): h_get_annotation_biomart works as expected ──
  `result` not identical to `expected`.
  Component "size": Mean relative difference: 0.005068424
  ── Failure (test-connections.R:84:3): h_get_size_biomart works as expected ─────
  h_get_size_biomart(...) not identical to c(`11185` = 3376L, `10677` = 5889L).
  1/2 mismatches
  [2] 5919 - 5889 == 30
  ── Failure (test-connections.R:92:3): h_get_size_biomart works as expected ─────
  h_get_size_biomart(...) not identical to c(ENSG00000135407 = 5889L, ENSG00000215417 = 3774L).
  1/2 mismatches
  [1] 5919 - 5889 == 30
  
  [ FAIL 3 | WARN 0 | SKIP 16 | PASS 832 ]
  Error: Test failures
  Execution halted
```

System information:

Field | Value
-- | --
Platform | x86_64-pc-linux-gnu (64-bit)
R Version | R version 4.1.2 (2021-11-01)
R Binary | /usr/local/bin/R
Rscript Binary | /usr/local/bin/Rscript
R Libraries | /opt/rlibs/nest_release/libs, /opt/rlibs/nest_release/libs
Start Timestamp | Mon 17 Jan 2022 05:21:52 PM UTC
End Timestamp | Mon 17 Jan 2022 06:31:04 PM UTC

### PR DESCRIPTION
**Pull request by danielinteractive**
closes #163

### CODE REVIEW

**Comment by danielinteractive** [comment]
@dinakar29 can you maybe double check here the updates for the version numbers etc? thx

**Comment by dinakar29** [comment]
> @dinakar29 can you maybe double check here the updates for the version numbers etc? thx

Apologies, I am actually very unfamiliar with the Ensembl marts and the BioMart data API, but I trust that you've got the versions correct.

**Comment by pawelru** [comment]
> > @dinakar29 can you maybe double check here the updates for the version numbers etc? thx
> 
> Apologies, I am actually very unfamiliar with the Ensembl marts and the BioMart data API, but I trust that you've got the versions correct.

Is it correct? Is this the right moment to increase it to the target version number? Thought we will do this at the end of UAT (which is a little bit risky though).
If we start now with (the target) 0.99.5 then auto bump-ups would increase it into 0.99.5.0.XX which we would then need to _downgrade_ into 0.99.5. Again, I am not so sure how our system would behave on pushing downgraded version number.

**Comment by danielinteractive** [comment]
> > > @dinakar29 can you maybe double check here the updates for the version numbers etc? thx
> > 
> > 
> > Apologies, I am actually very unfamiliar with the Ensembl marts and the BioMart data API, but I trust that you've got the versions correct.
> 
> Is it correct? Is this the right moment to increase it to the target version number? Thought we will do this at the end of UAT (which is a little bit risky though). If we start now with (the target) 0.99.5 then auto bump-ups would increase it into 0.99.5.0.XX which we would then need to _downgrade_ into 0.99.5. Again, I am not so sure how our system would behave on pushing downgraded version number.

@dinakar29 @pawelru yeah that was my question - about the R package version number.

**Comment by pawelru** [comment]
It seems that it's a blocker for docker creation and UAT installs. @danielinteractive can you please revert version number for a while so that @arkadiuszbeer can move on? Then we can clarify when to do it.

**Comment by danielinteractive** [comment]
> It seems that it's a blocker for docker creation and UAT installs. @danielinteractive can you please revert version number for a while so that @arkadiuszbeer can move on? Then we can clarify when to do it.

@pawelru please push on this branch as needed to correct it, then you have full control. also feel free to approve and merge

**Review by pawelru — APPROVED** [review]

**Pull request merged**
